// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkHy5lx8MDGjT8LHxBzcFs1j0aUG11k1M',
    appId: '1:482068425573:web:5eddac139ec8f6b5758f8c',
    messagingSenderId: '482068425573',
    projectId: 'spotifyclone24',
    authDomain: 'spotifyclone24.firebaseapp.com',
    storageBucket: 'spotifyclone24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLQSZehucE91TtiHalHHVCN6D7dBc4iQ8',
    appId: '1:482068425573:android:d29f5fefe045d623758f8c',
    messagingSenderId: '482068425573',
    projectId: 'spotifyclone24',
    storageBucket: 'spotifyclone24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxKzVu_uSNmALnnyYzGyhZbz-aOi5hzJ4',
    appId: '1:482068425573:ios:3d0e0d2452b80c37758f8c',
    messagingSenderId: '482068425573',
    projectId: 'spotifyclone24',
    storageBucket: 'spotifyclone24.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxKzVu_uSNmALnnyYzGyhZbz-aOi5hzJ4',
    appId: '1:482068425573:ios:3d0e0d2452b80c37758f8c',
    messagingSenderId: '482068425573',
    projectId: 'spotifyclone24',
    storageBucket: 'spotifyclone24.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkHy5lx8MDGjT8LHxBzcFs1j0aUG11k1M',
    appId: '1:482068425573:web:f3e41c32d83a3ff0758f8c',
    messagingSenderId: '482068425573',
    projectId: 'spotifyclone24',
    authDomain: 'spotifyclone24.firebaseapp.com',
    storageBucket: 'spotifyclone24.appspot.com',
  );
}
